### ISSUE TITLE
Preserve Host Headers

### ISSUE THREAD

**Issue by Peter-Puck** [axsuul/rails-reverse-proxy#15]
Hello, and thanks for this gem! Can rails-reverse-proxy be configured to always preserve the host:header (ie the equivalent of apache's "ProxyPreserveHost" setting)?

**Comment by axsuul** [comment]
Hello :) There's no option to do that specifically but you can definitely pass in a `Host` header. So perhaps something like this is what you're looking for?

```ruby
reverse_proxy 'http://1.2.3.4', headers: { 'Host' => request.host }
```

...orr can I learn more about your use case to better understand what you're looking for?

**Comment by Peter-Puck** [comment]
We're using the gem to do a reverse proxy to Jasper Reports i.e.:
reverse_proxy "http://JasperServer:8080/jasperserver" do |config|
[...]

When this reverse proxy is configured in either Apache or the rails-reverse-proxy gem, we get an infinite redirect loop.  In Apache, we can set the ProxyPreserveHost option to true which fixes this issue.  Unfortunately, passing in the header doesn't resolve the issue for this gem.  We've even tried setting target_request_headers['HOST'] = "hostname:port" in the client.rb.

**Comment by Peter-Puck** [comment]
Figured it out -- Jasper Server was expecting "OWASP_CSRFTOKEN" as a header, but OWASP-CSRFTOKEN was being passed (with the hyphen rather than the underscore).

We created the following def to solve:

  def getHeaders(request)
    result = { 'HOST' => request.headers['HOST'] }
    if (request.headers['OWASP-CSRFTOKEN'] != nil)
      result['OWASP_CSRFTOKEN'] = request.headers['OWASP-CSRFTOKEN']
    end
	result
  end

**Comment by axsuul** [comment]
That's great!
