### ISSUE TITLE
CookieJar cannot parse max-age attributes

### ISSUE THREAD

**Issue by miyukki** [axsuul/rails-reverse-proxy#2]
## Problem
This gem return internal server error when return the cookies including max-age attributes from proxying server.

Raised error line is here: https://github.com/axsuul/rails-reverse-proxy/blob/master/lib/reverse_proxy/client.rb#L95

The cause is CookieJar does not support max-age attributes of cookies.
https://github.com/dwaite/cookiejar

This issue is opened 11 months ago. But it is not maintained for a long time.
https://github.com/dwaite/cookiejar/pull/18

The is the specification of cookies is here: http://tools.ietf.org/html/rfc6265

## Example
```
irb(main):020:0> cookie = CookieJar::CookieValidation.parse_set_cookie('name=value; domain=.example.com; path=/; HttpOnly; Secure')
=> {:name=>"name", :value=>"value", :domain=>".example.com", :path=>"/", :http_only=>true, :secure=>true, :version=>0}
irb(main):021:0> cookie = CookieJar::CookieValidation.parse_set_cookie('name=value; domain=.example.com; path=/; HttpOnly; Secure; Max_Age=63072000')
CookieJar::InvalidCookieError: Unknown cookie parameter 'max_age'
	from /Users/Sakura/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/cookiejar-0.3.2/lib/cookiejar/cookie_validation.rb:324:in `block in parse_set_cookie'
	from /Users/Sakura/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/cookiejar-0.3.2/lib/cookiejar/cookie_validation.rb:297:in `each'
	from /Users/Sakura/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/cookiejar-0.3.2/lib/cookiejar/cookie_validation.rb:297:in `parse_set_cookie'
	from (irb):21
	from /Users/Sakura/.rbenv/versions/2.0.0-p481/bin/irb:12:in `<main>'
irb(main):022:0> 
```

## Solution
1. Using the forked gem. ex) https://github.com/elkatwork/cookiejar/commits/master
2. Using the another gem or library.
3. Parsing the cookies in this gem.

----

I'm troubled this issue. Please tell me your opinion for a way to solve.

**Comment by axsuul** [comment]
Thanks for bringing up this issue. I think we should probably move over the parsing logic into this gem so we can remove the `cookiejar` dependency. Besides, the code is only this long: https://github.com/dwaite/cookiejar/blob/master/lib/cookiejar/cookie_validation.rb#L292-L330

I can implement it this weekend but I will gladly also accept a pull request :) Thoughts?

**Comment by miyukki** [comment]
@axsuul Okay, I try to creating a pull request that add the parsing logic.

**Comment by axsuul** [comment]
@miyukki Thanks let me know if you have any questions! Much appreciated!
