### ISSUE TITLE
Unused rack-proxy dependency

### ISSUE THREAD

**Issue by chytreg** [axsuul/rails-reverse-proxy#20]
I've noticed that the library is dependent on `rack-proxy` but I can't find any reference in the code where it is used. Is `rack-proxy` gem needed?

**Comment by axsuul** [comment]
You're absolutely right--good eye! And I forget why the dependency is there. 

Since we don't have tests yet, do you mind forking the repo, removing the dependency, and then pointing the gem to that repo, using it, and then letting me know if everything still works?

**Comment by axsuul** [comment]
@chytreg I'd rather not remove the dependency for now in fear of breaking something. Would be happy to re-open this if someone could use this gem without this dependency and report back on results. Thanks.

**Comment by tomprats** [comment]
I'll try this next week (commenting now so I can find this issue again easier)

**Comment by axsuul** [comment]
@tomprats Sounds good, feel free to re-open! 👍
