### ISSUE TITLE
Confusing documentation

### ISSUE THREAD

**Issue by garmoshka-mo** [axsuul/rails-reverse-proxy#21]
```
match 'blog/*path' => 'wordpress#index', via: [:get, :post, :put, :patch, :delete]
```

It must be specified, that in this case `params` should be passed like

```
    reverse_proxy 'http://...', params do |config|
```

Currently user have to debug why `match` doesn't work

**Comment by starrychloe** [comment]
That doesn't work.

    reverse_proxy url, params, path: "fecms/", headers: { 'Host' => 'localhost:81', 'Referer' => url } do |config|

Gives

    ArgumentError (wrong number of arguments (given 3, expected 1..2)):

**Comment by axsuul** [comment]
Right now how `reverse_proxy` works is it expects you to pass in your headers and params manually. Would it be more user-friendly if there was a second method `respond_with_reverse_proxy` that takes care of it for you?

**Comment by axsuul** [comment]
@garmoshka-mo

**Comment by starrychloe** [comment]
I would say just add 10 more examples to the documentation using every possible combination of parameters and headers.

**Comment by axsuul** [comment]
If anyone wants to suggest an example I'll be happy to add it. Definitely don't want to add 10 examples that might not even see a use case for.

**Comment by axsuul** [comment]
Closing for now, feel free to re-open
