### ISSUE TITLE
request_parameters and query_parameters are not forwarded

### ISSUE THREAD

**Issue by aledalgrande** [axsuul/rails-reverse-proxy#22]
As per title, we have to manually attach GET and POST/PATCH parameters to the request, otherwise they are not forwarded.

**Comment by axsuul** [comment]
Right now how `reverse_proxy` works is it expects you to pass in your headers and params manually. Would it be more user-friendly if there was a second method `respond_with_reverse_proxy` that takes care of it for you?

**Comment by axsuul** [comment]
Closing for now, feel free to re-open
