### ISSUE TITLE
Relative path and redirects from the page do not work

### ISSUE THREAD

**Issue by germanyesid** [axsuul/rails-reverse-proxy#24]
Hi

Relative path and redirects from the page do not work, point to the root of the dominion. For example, if the initial path is /blog/, when the page redirects to index.xhtml it looks for the resource in /index and not in /blog/ index. In the same way, resources like .js .css are searched in the root and not in the current location, therefore the page does not load correctly.

How can i fix this?

Thank you

Sorry for my bad english

**Comment by axsuul** [comment]
Can you paste the code you're using so I can verify this?

**Comment by axsuul** [comment]
Closing, feel free to re-open if you're still experiencing this.
