### ISSUE TITLE
Does not seem to support SNI for SSL connections

### ISSUE THREAD

**Issue by starrychloe** [axsuul/rails-reverse-proxy#25]
When I try to reverse-proxy a SSL site, I get an error:

> Misdirected Request
>The client needs a new connection for this request as the requested host name does not match the Server Name Indication (SNI) in use for this connection.

SNI is like HOST header for HTTP, but for TLS protocol. 

https://en.wikipedia.org/wiki/Server_Name_Indication

Here is the code

```
class CmsController < ApplicationController
  include ReverseProxy::Controller

  def index
    # logger.debug request.path
    url = "http://localhost:81"
    url = "https://cms.mydomain.com" if Rails.env == 'production'

    reverse_proxy url do |config|
    end
```

It works in DEV because it doesn't use a SSL site. The HTTPS site works directly in the browser. However, it doesn't work in production through this gem because it uses an SSL site.

**Comment by axsuul** [comment]
@starrychloe Can you please try this branch and see if this fixes it for you?

https://github.com/axsuul/rails-reverse-proxy/tree/feature/sni

**Comment by craineum** [comment]
@axsuul FYI, setting the 'Host' header when calling the reverse_proxy allows SSL to work for me, so I would assume your fix will make this work.

**Comment by tomprats** [comment]
I had a similar issue but the linked branch didn't fix it for me. Instead doing `request.env.delete("HTTP_HOST")` before `reverse_proxy` worked

**Comment by starrychloe** [comment]
This works:

    url = "http://localhost:81"
    headers = {}
    if Rails.env == 'production'
      url = "https://different.production.site"
      headers = {'Host' => 'different.production.site'}
    end

    reverse_proxy url, headers: headers do |config|
      ...

**Comment by axsuul** [comment]
Closing this for now, feel free to re-open if still seeing issues
