### ISSUE TITLE
How to rewrite response?

### ISSUE THREAD

**Issue by kyleramirez** [axsuul/rails-reverse-proxy#26]
Hey there, thanks so much for putting this gem out. In the response body, I'd like to rewrite all occurrences of `http://localhost` to `http://localhost:3000` before being finally returned to the browser. Is this possible?

**Comment by fernandomm** [comment]
You can use something like this:

```
    reverse_proxy "http://localhost:3000" do |config|
      config.on_response do |code, response|
        response.body = '<h1>Example</h1>'
      end
    end
```

This would change all responses to \<h1\>Example\<\/h1\>.

In your case, you would probably use something like response.body.gsub!('http://localhost:3000', 'http://localhost')

**Comment by axsuul** [comment]
Thanks @fernandomm for chiming in. @kyleramirez can I close this or do you still need assistance?

**Comment by kyleramirez** [comment]
@axsuul Sorry for the delay! You are welcome to close the issue. Thanks so much for checking in.
