### ISSUE TITLE
Adding callback overrides default

### ISSUE THREAD

**Issue by tomprats** [axsuul/rails-reverse-proxy#31]
Adding a callback like below will override the default version. Is there a way to perform the default callback and then run the custom one?

I ran into this problem with CORS. Before the request I copy the CORS headers that a rack middleware produces and then `on_response` I add them back in. But doing this in an `on_response` callback overrode the original callback that added the headers to the response.

```
class WordpressController < ApplicationController
  include ReverseProxy::Controller

  def index
    # Assuming the WordPress server is being hosted on port 8080
    reverse_proxy "http://localhost:8080" do |config|
      config.on_response do |code, response|
        headers["Override"] = "This Header"
      end
    end
  end
end
```

I'd be willing to help submit a PR for this. I think the solution would be to have have each callback be a stack and then it'd call them sequentially. If backwards compatibility needs to be maintained, we can add a parameter with the option to override the current stack (defaulting to true for now). Then I could just do:

```
class WordpressController < ApplicationController
  include ReverseProxy::Controller

  def index
    # Assuming the WordPress server is being hosted on port 8080
    reverse_proxy "http://localhost:8080" do |config|
      config.on_response(override: false) do |code, response|
        headers["Override"] = "This Header"
      end
    end
  end
end
```

**Comment by axsuul** [comment]
Hi @tomprats 

Sorry, I'm having trouble understanding the issue you're running into. When you mention the original callback, are you referring to `on_response`? The `on_response` callback doesn't do anything by default.

Could you also show the code involving the CORS header? Thanks!

**Comment by tomprats** [comment]
I think I was referring to this default: https://github.com/axsuul/rails-reverse-proxy/blob/178b94776c0cf934caff927bd77bfbece926a33f/lib/reverse_proxy/controller.rb#L9

Here's my current solution around it:

```
class ProxyController < ApplicationController
  def index
    cors_headers = [
      "Access-Control-Allow-Headers",
      "Access-Control-Allow-Origin",
      "Access-Control-Allow-Methods",
      "Access-Control-Expose-Headers",
      "Access-Control-Max-Age",
      "Access-Control-Allow-Credentials",
      "X-Rack-CORS",
      "Vary"
    ]
    response_headers = response.headers.select{ |key| key.in? cors_headers }

    # this header should not be forwarded by the reverse proxy
    request.env.delete("HTTP_HOST")

    options = {
      username: "abc",
      password: "xyz",
      path: request.original_fullpath
    }

    reverse_proxy Traitify.host, options do |config|
      config.callbacks[:original_on_response] = config.callbacks[:on_response]
      config.on_response do |payload|
        config.callbacks[:original_on_response].call(payload)

        response_headers.each{ |key, value| headers[key] = value }
      end
    end
  end
end
```

Sorry about missing this for nearly a year. I only found it by scrolling through all my Github issues today

**Comment by axsuul** [comment]
@tomprats No problem, thanks for posting your workaround!

I'll close this issue for now but feel free to re-open if needed.
