### ISSUE TITLE
NameError: uninitialized constant ReverseProxy::Controller::Addressable

### ISSUE THREAD

**Issue by bapirex** [axsuul/rails-reverse-proxy#4]
from /ruby/2.1.0/gems/rails-reverse-proxy-0.5.0/lib/reverse_proxy/controller.rb:4:in `reverse_proxy'

There seems to be an issue with not having the "Addressable" gem not being required as part of controller.rb

Forgive me if this is incorrect, but adding the line to controller.rb makes this issue go away. That said, 

this "workaround" produces this additional error:

NameError: undefined local variable or method `env' for #<Object:0x00000008693c48>
        from /ruby/2.1.0/gems/rails-reverse-proxy-0.5.0/lib/reverse_proxy/controller.rb:58:in `reverse_proxy'

Which would imply it's this line:

client.request(env, options)

**Comment by axsuul** [comment]
Can provide any code in how you're using it?

**Comment by axsuul** [comment]
Are you still having this issue?

**Comment by bapirex** [comment]
@axsuul 

I'm really sorry, for some reason, I didn't get any update emails.

I am still having this issue.

The way I'm using this is as follows:

`class Statistic
  include ReverseProxy::Controller

  def forward
    reverse_proxy "http://localhost:9090/api/v1/query/", headers: {'Authorization'=> "Basic YWRtaW46YWRtaW4="} do |config|
      # We got a 404!
      config.on_missing do |code, response|
        redirect_to root_url and return
      end
    end
  end
end
`

**Comment by axsuul** [comment]
You'll need `Statistic` to extend `ActionController::Base` or `ApplicationController`

**Comment by bapirex** [comment]
@axsuul 

Thank you! This solved my problem. I still had to add 
```ruby
require "addressable/uri"
```
to **controller.rb** otherwise, it threw an exception.

I now have an issue with capitalize not working... The line in **client.rb** is 

```ruby
      target_request = Net::HTTP.const_get(source_request.request_method.capitalize).new(uri.request_uri)
```

I once again have no idea why this is the case considering this is a built in method... Any suggestions?

P.S. Thank you for helping me sort this out, given that my issues were entirely related to me being new to rails dev and nothing on your end...

**Comment by axsuul** [comment]
Oh, sorry. It looks like I missed part of you code. 

`reverse_proxy` is meant to be used in a controller and not a model. So that means you should be using it in `Api::V1::StatisticsController`. So something like:

```ruby
class Api::V1::StatisticsController < Api::BaseController
  include ReverseProxy::Controller

  version 1

  swagger_controller :stat, 'Statistics'

  swagger_api :index do
    summary 'Query the stats database'
  end

  def index
    reverse_proxy "http://localhost:9090/api/v1/query/", headers: {'Authorization'=> "Basic YWRtaW46YWRtaW4="} do |config|
      # We got a 404!
      config.on_missing do |code, response|
        redirect_to root_url and return
      end
    end
  end
end
```

**Comment by axsuul** [comment]
Also pushed a new version `0.5.1` that takes care of the `require 'addressable/uri` issue you were having. Please try that, thanks!

**Comment by bapirex** [comment]
Thanks for pushing out the fix so quickly!

Unfortunately I still run into the capitalize issue...

It's entirely possible that this is a conflict with https://github.com/Sutto/rocket_pants

I'll report back.

**Comment by axsuul** [comment]
So were you still experiencing this issue? Or can I close this? :)

**Comment by bapirex** [comment]
@axsuul You can most definitely close this :)
