### ISSUE TITLE
Unused Rack Proxy dependency?

### ISSUE THREAD

**Issue by semaperepelitsa** [axsuul/rails-reverse-proxy#43]
You are loading `rack-proxy` library, but I don't see it actually being used anywhere. Can it be removed?

**Comment by njaczko** [comment]
See https://github.com/axsuul/rails-reverse-proxy/issues/20

**Comment by mediafinger** [comment]
Solved with https://github.com/axsuul/rails-reverse-proxy/issues/45 and released as `0.10.1`

**Comment by axsuul** [comment]
Thanks @mediafinger !
