### ISSUE TITLE
Rails dependency unnecessary

### ISSUE THREAD

**Issue by mediafinger** [axsuul/rails-reverse-proxy#44]
While trying to work around the mimemagic yanking mess, I was about to replace:

```ruby
gem "rails", "~> 6.0.3"
```

with

```ruby
rails_version = "6.0.3"
gem "actionpack", "~> #{rails_version}"
gem "activejob", "~> #{rails_version}"
gem "activemodel", "~> #{rails_version}"
gem "activerecord", "~> #{rails_version}"
gem "railties", "~> #{rails_version}"
```

in our Gemfiles. Unfortunately one of our projects uses this rails-reverse-proxy gem, which has all of `rails` as a runtime dependency. Without looking at the code, I am sure this is unnecessary. Probably depending on `actionpack` alone would be sufficient.

Any chance to be a bit lighter on the dependencies?

**Comment by axsuul** [comment]
@mediafinger Hey yep that sounds like a great idea. Would you be able to test it on your end and submit a PR for this?

**Comment by mediafinger** [comment]
https://github.com/axsuul/rails-reverse-proxy/pull/45

**Comment by axsuul** [comment]
Merged via https://github.com/axsuul/rails-reverse-proxy/pull/45
