### ISSUE TITLE
Keep getting 404

### ISSUE THREAD

**Issue by royzinn** [axsuul/rails-reverse-proxy#5]
Hi and thanks for sharing this gem.
I have followed the instructions, trying to make my site ```weski.co.il/blog``` to reverse-proxy our WP which is hosted on different url.
my current controller action looks like this:
```ruby
reverse_proxy "http://roy.zebra-media.co.il/", path: params[:path] ,username: 'xxx', password: 'xxxxxxxxxxxx' do |config|
  config.on_missing do |code, response|
    redirect_to root_path and return
  end
end
```
It keeps redirecting me to ```root_path``` no matter what valid blog path I provide it.
Any ideas what can it be?

Thanks!

**Comment by bapirex** [comment]
If you look in the code, the on_missing callback checks the HTTP Status code returned.
```ruby
      when 400..499
        callbacks[:on_missing].call(payload)
```
The thing is that, this captures everything under the sun from a bad request to an actual 404. It might be worth checking the response headers by performing a curl request with the **-I** flag and report back.

**Comment by royzinn** [comment]
@bapirex - thanks for the quick response.
Before trying this gem, I used https://github.com/waterlink/rack-reverse-proxy which does reverse proxy but didn't allow me to set the headers, but the code is almost the same. I have initialized it with the same params and it works fine. 
Not sure how ```curl``` will help here. can u please explain how you would use ```curl``` in this particular case (I guess just ```curl``` the url with params will work just fine as it works now (weski.co.il/blog/ is currently reverse-proxying using the above gem)

**Comment by axsuul** [comment]
Can you let us know what `code` is here?

```ruby
reverse_proxy "http://roy.zebra-media.co.il/", path: params[:path] ,username: 'xxx', password: 'xxxxxxxxxxxx' do |config|
  config.on_missing do |code, response|
    # code?
    redirect_to root_path and return
  end
end
```

**Comment by royzinn** [comment]
@axsuul - didn't put any code there except for ```byebug``` to try and understand what's going on there

**Comment by axsuul** [comment]
@royzinn Sorry, I meant can you give us the value for `code` variable?

**Comment by axsuul** [comment]
@royzinn Any updates on this?

**Comment by royzinn** [comment]
Hi @axsuul, 
Sorry for the delayed response, I somehow missed the latest discussion.
The code is 402. The strange part is that I don't see any request goes "out" it looks like the response immediately replied,
Maybe I missed something in the configuration although I followed the instructions.

**Comment by axsuul** [comment]
Hmm that's quite an odd code. `402` is **Payment Required**? Do you know why it could be returning this type of code?

**Comment by royzinn** [comment]
sorry, my mistake, it is 404...autocomplete :-)

**Comment by axsuul** [comment]
Sorry want to get to the bottom of this. Could it be that you're passing a bad argument to `path`? What is `params[:path]` for you?

**Comment by royzinn** [comment]
I have ```params[:path] = what-makes-val-thorens-so-special```
so, to make everything clear, I'm trying my app url to reverse proxy to http://roy.zebra-media.co.il so that:
```localhost:3000/blog/``` will fetch http://roy.zebra-media.co.il/ 
and
```localhost:300/blog/val-thorens-activities-and-things-to-do``` will fetch http://roy.zebra-media.co.il/val-thorens-activities-and-things-to-do

Thanks for looking into this :-)

**Comment by axsuul** [comment]
May have found the issue. So how this gem works is it's trying to make a TCP request to 

```
http://roy.zebra-media.co.il/val-thorens-activities-and-things-to-do:80
```

Notice the `:80`. When trying to access this URL with the port, it gives a **404**. Are you able to make it so that the `:80` URL also works?

**Comment by royzinn** [comment]
Hi @axsuul  - thanks for looking into the issue.
unfortunately, I'm not sure I can deal with it now as it's on low priority and i'm in the process of bootstrapping the company. 
I know it's not fair that i'm not contributing further to the effort you put in this gem (which is highly appreciated) but it might take me a while.
I would love to come back at it later on and update you with the results.
Thanks much,
Roy

**Comment by axsuul** [comment]
No worries @royzinn. Hope you don't mind me closing this for the time being. Feel free to open it in the future when you come back to it. Thanks! 👍

**Comment by yochze** [comment]
Hey,
I am also keep getting `404` on a custom (non `80`) port. @axsuul Any idea what should I do?

**Comment by axsuul** [comment]
@yochze Can you paste some code? What's being hosted on the non`80` port?

**Comment by yochze** [comment]
Hey, I am running Jupyter Notebooks on port 80

This is my reverse proxy method (here it's 8080 and it doesnt work. If I restart Jupyter with  80, it works)
```
def show
        reverse_proxy "http://127.0.0.1:8080/path/path/path/", path: params[:yo_path], verify_ssl: false, headers: { 'Authorization' => 'token Aaaa...' } do |config|

            config.on_missing do |code, response|
                redirect_to root_url and return
            end
        end
```

Also, a bit off current topic, is it possible to extend this gem to support Websockets (like https://github.com/nodejitsu/node-http-proxy)?

**Comment by pyadav** [comment]
@zigomir  Thanks  👍
