### ISSUE TITLE
Exception occured: URI::InvalidURIError - bad URI(is not URI?)

### ISSUE THREAD

**Issue by bapirex** [axsuul/rails-reverse-proxy#6]
So, let's assume that I perform a GET for the url: ``http://blah.com/api/v1/series%3fmatch%5b%5d%3dup%26match%5b%5d%3dprocess_start_time_seconds%7bjob%3d%27prometheus%27%7d``

The way the route is set up, the
path parameter returns 
``"series?match[]=up&match[]=process_start_time_seconds{job='prometheus'}"``

My index method contains this:

```ruby
 reverse_proxy "http://localhost:9090/api/v1/", path: params[:path], headers: {'Authorization'=> "Basic YWRtaW46YWRtaW4="} do |config|
      config.on_missing do |code, response|
        redirect_to('/') && return
      end
```
I get the error
``Exception occured: URI::InvalidURIError - bad URI(is not URI?): http://localhost:9090/api/v1/series?match[]=up&match[]=process_start_time_seconds{job='prometheus'}``

I'm fairly certain it's because of all the invalid url characters in the query.

**Comment by axsuul** [comment]
Hmm, can you tell me which line is throwing that error?

**Comment by bapirex** [comment]
This is an excerpt from the backtrace:
``
ERROR -- : Exception backtrace:
ERROR -- : => /usr/lib/ruby/2.1.0/uri/common.rb:176:in `split'
ERROR -- : => /usr/lib/ruby/2.1.0/uri/common.rb:211:in `parse'
ERROR -- : => /usr/lib/ruby/2.1.0/uri/common.rb:747:in `parse'
ERROR -- : => /var/www/app/vendor/bundle/ruby/2.1.0/gems/rails-reverse-proxy-0.5.1/lib/reverse_proxy/client.rb:48:in `request'
ERROR -- : => /var/www/app/vendor/bundle/ruby/2.1.0/gems/rails-reverse-proxy-0.5.1/lib/reverse_proxy/controller.rb:59:in `reverse_proxy'
ERROR -- : => /var/www/app/app/controllers/api/v1/statistics_controller.rb:14:in `index'
``

**Comment by axsuul** [comment]
If you try doing this

```ruby
reverse_proxy "http://localhost:9090/api/v1/", path: "series?match[]=up&match[]=process_start_time_seconds{job='prometheus'}", headers: { 'Authorization'=> "Basic YWRtaW46YWRtaW4=" } do |config|
      config.on_missing do |code, response|
        redirect_to('/') && return
      end
```

does it still raise the same error?

**Comment by bapirex** [comment]
@axsuul Yep, it does.

**Comment by axsuul** [comment]
Can I ask what ruby version you're on?

**Comment by bapirex** [comment]
@axsuul 
Sure, it's:
Ruby 2.1 & Rails 4.2.0

**Comment by axsuul** [comment]
Hmm I'm having issues reproducing the error. So if you get rid of those special characters in the `path`, the error goes away?

**Comment by bapirex** [comment]
@axsuul I caught the error! I'll submit a pull request :)

**Comment by axsuul** [comment]
@bapirex Great, looking forward to it :)
